[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' data: https://*.netlify.app/;
      style-src 'self';
      object-src 'none';
      frame-src https://*.netlify.app/ https://*.netlify.com/;
    '''
    Feature-Policy = "fullscreen 'self'"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
